{% set version = "6.0.0" %}
{% set sha256 = "1ff53c915b4e761ef400b803f07261ade637b0c269d99569f18040f3dcee4408" %}

{% set llvm_variant = os.environ.get('LLVM_VARIANT', 'default') %}
{% set build_number = "0" %}

package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - llvm-lto-static.patch   # [win]
{% if llvm_variant == "cling" %}
    - cling-patches/0001-Add-interface-to-create-DyLib-from-dlopen-handle.patch
    - cling-patches/0002-Add-cling-as-tool-to-be-built.patch
    - cling-patches/0003-Do-NOT-remove-original-functions-after-inlining-them.patch
    - cling-patches/0004-From-Lang-Hames-first-step-towards-RuntimeDyld-resol.patch
    - cling-patches/0005-Update-DEBUG-to-current-llvm-API.patch
    - cling-patches/0006-Mark-weak-symbols-weak-apparently-NFC.patch
    - cling-patches/0007-Weak-undefined-symbols-should-not-trigger-the-emissi.patch
    - cling-patches/0008-Adapt-to-llvm-r272382.patch
    - cling-patches/0009-Enable-unicode-output-on-terminals.patch
{% endif %}

build:
  number: {{ build_number }}
  string: {{ llvm_variant }}_{{ build_number }}
  skip:  true  # [py<36]

{% if llvm_variant == "cling" %}
  features:
    - cling
    - vc14     # [win and py36]
{% else %}
  features:    # [win and py36]
    - vc14     # [win and py36]
{% endif %}

requirements:
  build:
    - toolchain
    - cmake
    # Needed to unpack the source tarball
    - m2w64-xz  # [py27 and win]
    - ninja  # [win]
    # Needed to build LLVM
    - python
    - system  # [linux and not armv7l]
  run:
    - system  # [linux and not armv7l]
    - vc 14  # [win]
    - llvm-meta {{ version }}|{{ version }}.*

test:
{% if llvm_variant == "cling" %}
  requires:
    - cling-patches
    - python {{ environ['PY_VER'] + '*' }}                   # [win]
{% else %}
  requires:                                                  # [win]
    - python {{ environ['PY_VER'] + '*' }}                   # [win]
{% endif %}

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
    - isuruf
