{% set version = "6.0.1" %}
{% set sha256 = "b6d6c324f9c71494c0ccaf3dac1f16236d970002b42bb24a6c9e1634f7d0f4e2" %}

{% set build_number = 0 %}

package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - llvm-lto-static.patch   # [win]
    - twine_cfg_undefined_behavior.patch
    - D47188-svml.patch
{% if llvm_variant == "cling" %}
    - cling-patches/0001-Add-interface-to-create-DyLib-from-dlopen-handle.patch
    - cling-patches/0002-Add-cling-as-tool-to-be-built.patch
    - cling-patches/0003-Do-NOT-remove-original-functions-after-inlining-them.patch
    - cling-patches/0004-From-Lang-Hames-first-step-towards-RuntimeDyld-resol.patch
    - cling-patches/0005-Update-DEBUG-to-current-llvm-API.patch
    - cling-patches/0006-Mark-weak-symbols-weak-apparently-NFC.patch
    - cling-patches/0007-Weak-undefined-symbols-should-not-trigger-the-emissi.patch
    - cling-patches/0008-Adapt-to-llvm-r272382.patch
    - cling-patches/0009-Enable-unicode-output-on-terminals.patch
{% endif %}

build:
  number: {{ build_number }}
  skip:  true  # [vc<14]
  features:
    - cling    # [llvm_variant == 'cling']

outputs:
  - name: llvm-meta

  - name: llvmdev
    script: build_llvm.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja     # [win]
        - python
      host:
      run:
        - {{ pin_subpackage("llvm-meta", exact=True) }}

test:
  requires:
    - cling-patches    # [llvm_variant == 'cling']
  files:
    - numba-3016.ll

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

    - opt -S -vector-library=SVML -mcpu=haswell -O3 numba-3016.ll -o out.ll
    - findstr __svml_sin4 out.ll                             # [win]
    - grep __svml_sin4 out.ll                                # [unix]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
    - isuruf
