{% set shortversion = "5.0" %}
{% set version = "5.0.0" %}
{% set sha256 = "e35dcbae6084adcf4abb32514127c5eabd7d63b733852ccdb31e06f1373136da" %}

{% set build_number = 1002 %}

package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # https://llvm.org/bugs/show_bug.cgi?id=15356
    - llvm-elf-relocation.patch
    - llvm-lto-static.patch   # [win]

build:
  number: {{ build_number }}
  skip:  true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja     # [win]
    - python
  host:
    - llvm-meta {{ version }}
  run:
    - llvm-meta {{ version }}

test:
  requires:                                                  # [win]
    - python {{ environ['PY_VER'] + '*' }}                   # [win]

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
    - isuruf
