{% set version = "17.0.6" %}
{% set major_ver = version.split(".")[0] %}

package:
  name: llvm-package
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 58a8818c60e6627064f312dbf46c02d9949956558340938b71cf731ad8bc0813
  patches:
    - patches/0002-restore-macos-10.9-support.patch
    # This patches cmake code which isn't hit in the current configuration, however it's kept in case we want to build
    # libllvm-c in the future
    - patches/osx_ver.patch
    # A different approach to this fix: https://github.com/conda-forge/llvmdev-feedstock/commit/1da42e54b055d26bc58da77bd1f88ad460ac90f4
    - patches/MSVC_DIA_SDK_path_fix.diff  # [win]

build:
  number: 0
  merge_build_host: false

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python >=3
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - make      # [not win]
    - m2-coreutils  # [win]
    - m2-make   # [win]
    - m2-patch  # [win]
    - m2-grep   # [win]
    - m2-sed    # [win]
    - patch       # [not win]
    - m2-patch    # [win]
    - git         # [unix]
    - m2-git      # [win]
  host:
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - zlib 1.2.13
    - libxml2 2.10 # [win]
    - libffi 3.4   # [unix]

outputs:
  # Contains everything
  - name: llvmdev
    script: install_llvm.sh  # [not win]
    script: install_llvm.bat  # [win]
    build:
      skip: true  # [(win and vc<14)]
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python >=3
      host:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - {{ pin_subpackage("llvm-tools", exact=True) }}
        - zlib 1.2.13
      run:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - {{ pin_subpackage("llvm-tools", exact=True) }}
        - libcxx >={{ cxx_compiler_version }}  # [osx]
    test:
      commands:
        - $PREFIX/bin/llvm-config --libs                   # [not win]
        - test -f $PREFIX/include/llvm/Pass.h              # [not win]
        - test -f $PREFIX/lib/libLLVMCore.a                # [not win]
        - $PREFIX/libexec/llvm/not false                   # [not win]
        - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1  # [win]
        - if not exist "%LIBRARY_PREFIX%"\\libexec\llvm\not.exe exit 1  # [win]

  # Contains the shared libraries. To make different LLVM libraries co-installable
  # soversion is appended to the package name.
  - name: libllvm{{ major_ver }}
    script: install_llvm.sh  # [not win]
    build:
      skip: true  # [win and vc<14]
      activate_in_script: true
      run_exports:   # [not win]
        - {{ pin_subpackage("libllvm" + major_ver, max_pin="x.x") }}  # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - ninja                  # [not win]
        - cmake                  # [not win]
        - python >=3             # [not win]
      host:
        - libcxx >={{ cxx_compiler_version }}  # [osx]
        - zlib 1.2.13
        - libffi 3.4  # [unix]
      run:
        - libcxx >={{ cxx_compiler_version }}  # [osx]
        - libffi >=3.4,<3.5  # [unix]
        - zlib    # [osx]
    test:
      commands:
        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}${SHLIB_EXT}  # [not win]

  # This is a meta package so that people can use the latest libllvm and also
  # for run_exports
  - name: llvm
    build:
      skip: true  # [(win and vc<14)]
      run_exports:   # [not win]
        - {{ pin_subpackage("libllvm" + major_ver, max_pin="x.x") }}  # [not win]
    requirements:
      build:
      host:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}  # [not win]
        - zlib 1.2.13
      run:   # [not win]
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}  # [not win]
      run_constrained:             # [not win]
        - llvmdev   {{ version }}  # [not win]
    test:
      commands:
        - echo "Hello World!"

  # Contains LLVM tools
  - name: llvm-tools
    script: install_llvm.sh   # [not win]
    script: install_llvm.bat  # [win]
    build:
      skip: true  # [(win and vc<14)]
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python >=3
      host:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - libxml2 2.10  # [win]
        - zlib 1.2.13
      run:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
      run_constrained:
        - llvmdev   {{ version }}
    test:
      commands:
        - $PREFIX/bin/llc -version                               # [not win]
        - if not exist "%LIBRARY_BIN%"\\llc.exe exit 1           # [win]
        - llc -version                                           # [win]

  - name: lit
    build:
      script: python -m pip install llvm/utils/lit --no-deps -vv
      activate_in_script: true
      skip: true  # [py<30]
      entry_points:
        - lit = lit.main:main
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - lit
      commands:
        - lit -h

about:
  home: https://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://llvm.org/docs/
  license: Apache-2.0 WITH LLVM-exception
  license_file: llvm/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - jakirkham
    - mingwandroid
    - SylvainCorlay
    - isuruf
    - timsnyder
    - xhochy
    - h-vetinari
