{% set version = "14.0.0.tf280_55c71c9eac9b" %}
{% set major_ver = version.split(".")[0] %}
{% set git_commit = "55c71c9eac9bc7f956a05fa9258fad4f86565450" %}
{% if git_commit != "" %}
  {% set archive_file = git_commit %}
{% else %}
  {% set archive_file = "refs/tags/llvmorg-" + version.replace(".rc", "-rc") %}
{% endif %}

package:
  name: llvm-for-tensorflow
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/archive/{{ archive_file }}.tar.gz
    sha256: 1459d328ea67802f5b7c64349ba300b5ddc4a78838d6b77a8a970fe99ed3e78c

build:
  number: 0
  skip: true  # [win or ppc64le or aarch64]
  # conda-build breaks on this. There is no need to relocate anything, so skip it.
  binary_relocation: false

requirements:
  build:
    - python *
    - astor
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel 4.2.1
    - bazel-toolchain
    - rsync

test:
  commands:
    - test -f "${PREFIX}/lib/libLLVMTFSupport.a"
    - test -f "${PREFIX}/share/llvm_for_tf/llvm/BUILD.bazel"
    - test -f "${PREFIX}/share/llvm_for_tf/llvm/include/llvm/Pass.h"
    - test -f "${PREFIX}/lib/libMLIRTFSupport.a"
    - test -f "${PREFIX}/share/llvm_for_tf/mlir/BUILD.bazel"
    - test -f "${PREFIX}/share/llvm_for_tf/mlir/include/mlir/InitAllPasses.h"

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: Apache-2.0 WITH LLVM-exception
  license_file: llvm/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM, pre-built for use with tensorflow

extra:
  recipe-maintainers:
    - conda-forge/tensorflow
