appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: N3PMgkCAbqBPMfgsDc04XUBaHmxaHPihY9xEn0oKBM9nLN+mX6FbFNDYOtMf3mjpvutfyt6C5+9C3Cp5ET6wEFirnSBkdDs74qp0L3P9felfWMwh+PqrLYcQxf1FkEukLa0C5KQvbsEs4Qj+IZzetUDHRPzvKswGVN62kW2U80lEnaAuFQEb6M0ou61JEKifhH40tvOGlAYbG2jEAV86A6ANZFQSFuxd97Y15Ql8a7AY/Xys4Tf5L0IYtmP12/EB7gS1TWJJVyUojbv+5yaK4plP0ta2GavIQ770HCb/aWZtg/oyrnKQ9drwSyZq9h9ystRXtflLvCXRMaycnPoIHubaHDTJzcRwZ49JzUr/gh923S+b6K+106nl6vfITzwjK6h9W+qaJzxdahge4JIXZQdZ6uKR46QH7ksAE3J/q283UkB8S1v2/d66SAmu0QeAczDYr7k5XKrz3GZDtA5gtN4w0z5pdIp53sQh9GVu09GSBh74/ZdRdoMb5jBLcOkvo5ZMMc7KJDPl0NttbdwxvN2PvnDwJQDpQK4KLm2U1JDldf1suSP7eUfy2aTBGA/Be917xClez77MiL8+GHy8/rzVygpnekdnIIjJPFthxglqY6b846Yo+SVDd9BPKDrjpvCU5xg+BeMjq6jcoDyFOB93JAoDl0+dVHrjzubtwuE=}
