matrix:
- [[LLVM_VARIANT, cling]]
- [[LLVM_VARIANT, default]]
travis:
  secure:
    BINSTAR_TOKEN: DCEx+gVAmvgbY08W6g1mm4m1ajTP1+VpldjtA2XhTPM/ItnjY8E4OjjR6+V0ETzS3VeVdikTD0mXHwzpLaxHtz3u91Ohwx0hmTu1bPDeAGc9xJtWx92PmdyOAylKJM0syScdjngauZzFV2k2VjNb/zQceZCqM7pVo+16ncJNWM3zU3nUjz5ZIDm6NqF0+M5ML/DBwKqG/zu3RGppPPWhmI4OWpeEyTEHaqoRnED9imCiMqeKxAXnYQX6LKlnuUSU6SpTQ+sKaVRxxVl1LRgSYZQ+fQIe8AD7R86zR2cJajX3kojnwaU7TPurRR8s5HelXx+qCEKTJIaYgj8H164ECIU1OnQ/qy4YdwKp5n602DpRM2tctCGMhc1+ym8SvoJbm3TGmEK7wSaXKAVAVTn6qzPxFb8HA9DR3NyjKYXLa7I0rpO1f+LZ3NrM6iMHvuCRoplDOSmKcfqVlygPgWi/dpk+cohOII4yQPZufqQzQRVEdAB2+XDwnA6nMPBw0Vue7fiFdBvhgmHNlLgcjzF8pPWfjCYELXfxh25Fb2QwT3+Mo4bkeEa4KhTwIgm9ozCtpcCJKGsxS2HatrUNHNAwsgkML8fMRjSHHdh6cmB6AgpdZ9haR9AlHi7XKdjzkq3fv2c1uc77X44KOioAr9V9pTuvOoHDliSslnqICikdh4k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
